steps:
- task: NodeTool@0
  displayName: 'Use Node 8.x'
  inputs:
    versionSpec: 8.x

- task: Npm@1
  displayName: 'npm install'

- task: Npm@1
  displayName: 'Build'
  inputs:
    command: custom
    customCommand: run build

- task: Npm@1
  displayName: "Download language server"
  env:
    LANGUAGE_SERVER_DOWNLOAD_PATH: $(LANGUAGE_SERVER_DOWNLOAD_PATH)
  inputs:
    command: custom
    customCommand: run download-language-server
